### ISSUE TITLE
Needs to accept all options, especially --diff

### ISSUE THREAD

**Issue by benjaoming** [learningequality/black-fmt#2]
Invoking `black --check` doesn't show the source of an error. Invoking `black --check --diff` does. But the wrapper says "error: unknown option `--diff'"

**Comment by indirectlylit** [comment]
I don't think it's feasible to accept "all" of the options, so recommend limiting the scope of this issue. PR welcome though! :)

**Comment by benjaoming** [comment]
Yeah okay I thought of the option of just not actually validating options in the wrapper, but passing them on.. then `black` itself can fail.

**Comment by benjaoming** [comment]
Not sure if this is important, though, if my PR for `tox.ini` in Kolibri is accepted and we can skip this wrapper in CI.
