### ISSUE TITLE
Run black through pre-commit

### ISSUE THREAD

**Issue by benjaoming** [learningequality/black-fmt#3]
One of the design features of pre-commit is to create a separate Python environment for the linting tools. This means that Black can run outside of the development environment in some other Python version.

I would like to discuss the potential for replacing the need for this repository with "black through pre-commit", as per their official documentation. For more background on pre-commit, see the exchange here: https://github.com/psf/black/issues/1073

CC: @indirectlylit @ralphiee22

**Comment by benjaoming** [comment]
This would perhaps also fix a recurring confusion: What version of Black are we even running? As per https://github.com/learningequality/kolibri/pull/6004

**Comment by indirectlylit** [comment]
Yup, I tried that first. Black is limited to python 3.6+, so we were unable to use that strategy because some developers run early versions of Python 3.

ref: https://github.com/psf/black/issues/585

**Comment by benjaoming** [comment]
@indirectlylit can developers not be restricted to systems with Python 3.6+? This doesn't pertain their development virtualenv since pre-commit creates its own.

The fall-back mode would be that linting is also run in CI, so a PR would still error out if the developer has skipped using pre-commit.

**Comment by benjaoming** [comment]
The pre-commit hook is specified in the official PSF repo and doesn't pin Python 3.6.. but it has to be 3.6+, I suppose. 3.5 hasn't been around for quite a while?

https://github.com/psf/black/blob/master/.pre-commit-hooks.yaml

**Comment by indirectlylit** [comment]
> @indirectlylit can developers not be restricted to systems with Python 3.6+?

At the time that seemed like too much to ask, because the version of Ubuntu a few people were running came with 3.5

**Comment by benjaoming** [comment]
Let's find out :)

**Comment by indirectlylit** [comment]
> Let's find out :)

That's my point - we did it this way originally and I got 2 different complaints that things were broken. Specifically, I know @rtibbles ran into this problem.

also ref: https://github.com/learningequality/kolibri/issues/5409
